version: "3"
services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:$GOPATH/src
    working_dir: $GOPATH/src
    ports:
      - 11434:11434
  app:
    build: app
    tty: true
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8080
    command: ["go", "run", "main.go"]
