version: "3"
services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama:$GOPATH/src
    working_dir: $GOPATH/src
    ports:
      - 11434:11434
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    environment:
      - WEBUI_AUTH=False
    extra_hosts:
      - host.docker.internal:host-gateway
  app:
    build: app
    tty: true
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    extra_hosts:
      - host.docker.internal:host-gateway
